services:
  app:
    build: .
    tty: true
    stdin_open: true
    env_file:
      - production.env
    working_dir: /app
    restart: always
    volumes:
      - ./src:/app
    ports:
      - '3000:3000'
    depends_on:
      - db
      - minio
      - redis
    command: >
      bash -c "rm -f /app/tmp/pids/server.pid &&
      rm -rf /app/public/assets &&
      gem cleanup &&
      bundle install -j4 &&
      rails db:migrate &&
      RAILS_ENV=production rails assets:precompile &&
      rails s -b 0.0.0.0"

  front:
    image: node:lts
    tty: true
    stdin_open: true
    env_file:
      - production.env
    working_dir: /app
    restart: always
    volumes:
      - ./src2:/app
    ports:
      - '3001:3000'
    command: sh -c "npm install && npm update && npm run build && npm run start"

  db:
    image: mariadb:latest
    env_file:
      - production.env
    volumes:
      - db-vol:/var/lib/mysql
    stdin_open: true
    tty: true
    restart: always
    ports:
      - '3306:3306'

  phpmyadmin:
    image: phpmyadmin:latest
    env_file:
      - production.env
    ports:
      - '8080:80'
    stdin_open: true
    tty: true
    restart: always
    depends_on:
      - db

  minio:
    image: minio/minio:latest
    volumes:
      - minio-vol:/data
    command: server /data --console-address ":9001"
    env_file:
      - production.env
    stdin_open: true
    tty: true
    restart: always
    ports:
      - '9000:9000'
      - '9001:9001'

  redis:
    image: redis:latest
    volumes:
      - redis-vol:/data
    restart: always
    ports:
      - '6379:6379'

  rediscommander:
    image: rediscommander/redis-commander:latest
    environment:
      REDIS_HOSTS: 'sidekiq:redis:6379,sidekiq2:redis:6379'
      TZ: JST-9
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - redis

  sidekiq:
    build: .
    env_file:
      - production.env
    working_dir: /app
    volumes:
      - ./src:/app
    restart: always
    depends_on:
      - redis
    command: >
      bash -c "bundle install -j4 &&
      bundle exec sidekiq -C config/sidekiq.yml"

  meilisearch:
    image: getmeili/meilisearch:latest
    env_file:
      - development.env
    volumes:
      - meili-vol:/data.ms
    ports:
      - "7700:7700"

volumes:
  db-vol:
  minio-vol:
  redis-vol:
  meili-vol: