services:
  nextjs:
    build: ./frontend
    tty: true
    stdin_open: true
    env_file:
      - .env
    working_dir: /app
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
      - next:/app/.next
    ports:
      - 3000:3000
    command: sh -c "npm install && npm update && npm run dev"

  rails:
    build: ./backend
    tty: true
    stdin_open: true
    env_file:
      - .env
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - 3001:3000
    depends_on:
      - mariadb
      - minio
    command: >
      bash -c "rm -f /app/tmp/pids/server.pid &&
      rm -rf /app/public/assets &&
      gem cleanup &&
      bundle install -j4 &&
      rails s -b 0.0.0.0"

  mariadb:
    image: mariadb:latest
    tty: true
    stdin_open: true
    env_file:
      - .env
    volumes:
      - mariadb-vol:/var/lib/mysql
    ports:
      - 3306:3306

  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    tty: true
    stdin_open: true
    env_file:
      - .env
    volumes:
      - minio-vol:/data
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data --console-address ":9001"

  phpmyadmin:
    image: phpmyadmin:latest
    tty: true
    stdin_open: true
    env_file:
      - .env
    depends_on:
      - mariadb
    ports:
      - 8080:80

  meilisearch:
    image: getmeili/meilisearch:latest
    tty: true
    stdin_open: true
    env_file:
      - .env
    volumes:
      - meili-vol:/meili_data
    ports:
      - 7700:7700

volumes:
  node_modules:
  next:
  mariadb-vol:
  minio-vol:
  meili-vol:
